### ISSUE TITLE
X- AUTHENTICATION FAILED as admin (IPR)

### ISSUE THREAD

**Issue by epreom** [UndernetIRC/gnuworld#16]
can you help please

**Comment by epreom** [comment]
can i turn this feature off

**Comment by empus** [comment]
This is not a bug.  

If you don't want to enforce IPR unless a username has IPR entries, in `mod.cservice/cservice_config.h` change the line:

`#define IPR_DEFAULT_REJECT`

to:

`#undef IPR_DEFAULT_REJECT`

... and then recompile gnuworld.

Otherwise, add IPR entries to your 'admin' user in the `ip_restrict` table so you can login from the IP(s) you require.

In future, for general support queries, please ask in #coder-com on Undernet.

**Comment by epreom** [comment]
I did but the problem is still the same
#undef IPR_DEFAULT_REJECT
-X- AUTHENTICATION FAILED as Admin (IPR)

**Comment by epreom** [comment]
login process ok now this error pops up

-X- Unable to retrieve response. Please contact a cservice administrator.
-X- Unable to retrieve response. Please contact a cservice administrator.
-X- Unable to retrieve response. Please contact a cservice administrator.
-X- Unable to retrieve response. Please contact a cservice administrator.

**Comment by speakzzz** [comment]
I think language table is missing there, no?



Get BlueMail for Android
